In [3]:
import numpy as np

In [6]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [7]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

In [10]:
data.ndim

2

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
np.empty((2,3,2))

array([[[0.00000000e+000, 0.00000000e+000],
        [2.96439388e-323, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 8.34403734e-309]]])

In [14]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [16]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [17]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [18]:
arr -arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [20]:
arr2d[0, 2]

3

In [21]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [22]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])

In [23]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [24]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [25]:
data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [26]:
mask = (names == "Bob") | (names == "Will")

In [27]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [28]:
arr = np.zeros((8, 4))
for i in range(8): arr[i] = i

In [29]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [30]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [31]:
arr = np.arange(32).reshape((8, 4))

In [32]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [33]:
 arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [34]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [35]:
 arr = np.arange(15).reshape((3, 5))

In [36]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [37]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [38]:
np.dot(arr.T, arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [39]:
arr.T @ arr

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [40]:
arr.swapaxes(0, 1)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [41]:
samples = np.random.standard_normal(size=(4, 4))

In [43]:
samples

array([[-0.27460535, -1.56309626,  1.99415957, -1.95313331],
       [ 0.86017493,  0.41765545, -0.76763263,  1.14179931],
       [-0.89200341,  0.02476299,  0.3767159 , -0.42508322],
       [-1.15780413, -1.3316444 , -1.65546611, -1.07515231]])

In [44]:
arr = np.arange(10)

In [45]:
 np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [46]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [47]:
points = np.arange(-5, 5, 0.01)

In [49]:
xs, ys = np.meshgrid(points, points)

In [64]:
z = np.sqrt(xs ** 2 + ys ** 2)

In [65]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = np.where(cond, xarr, yarr)


In [66]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [68]:
arr = np.random.standard_normal((4, 4))

In [69]:
np.where(arr > 0, 2, -2)

array([[-2, -2,  2,  2],
       [ 2,  2, -2,  2],
       [-2, -2, -2, -2],
       [ 2,  2, -2,  2]])

In [70]:
arr.mean()

-0.10732838824499585

In [72]:
bools = np.array([False, False, True, False])

In [73]:
bools.any()

True

In [74]:
bools.all()

False

In [75]:
np.unique(names)


array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [76]:
values = np.array([6, 0, 0, 3, 2, 5, 6])

In [78]:
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

In [79]:
from numpy.linalg import inv, qr

In [81]:
X = np.random.standard_normal((5, 5))

In [82]:
mat = X.T @ X



In [83]:
inv(mat)

array([[ 16.86329845,  -0.18567506, -21.16570388,   9.0361449 ,
         12.19587766],
       [ -0.18567506,   0.71925509,   0.74631131,  -0.42963011,
          0.06329939],
       [-21.16570388,   0.74631131,  27.63674024, -11.67125733,
        -15.35829236],
       [  9.0361449 ,  -0.42963011, -11.67125733,   5.26781275,
          6.54490823],
       [ 12.19587766,   0.06329939, -15.35829236,   6.54490823,
          9.25823349]])

In [84]:
mat @ inv(mat)

array([[ 1.00000000e+00,  1.17961196e-16,  3.55271368e-15,
         0.00000000e+00,  1.77635684e-15],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         1.77635684e-15,  1.77635684e-15],
       [ 3.55271368e-15,  2.08166817e-17,  1.00000000e+00,
         2.66453526e-15,  6.66133815e-16],
       [-3.55271368e-15, -8.32667268e-17, -5.32907052e-15,
         1.00000000e+00, -3.55271368e-15],
       [ 0.00000000e+00,  1.66533454e-16, -7.10542736e-15,
        -3.55271368e-15,  1.00000000e+00]])

In [85]:
nsteps = 1000

In [86]:
rng = np.random.default_rng(seed=12345)

In [87]:
 draws = rng.integers(0, 2, size=nsteps)

In [89]:
steps = np.where(draws == 0, 1, -1)

In [90]:
 walk = steps.cumsum()

In [91]:
(np.abs(walk) >= 10).argmax()

155

In [92]:
nwalks = 5000

In [93]:
draws = rng.integers(0, 2, size=(nwalks, nsteps)) # 0 or 1

In [94]:
steps = np.where(draws > 0, 1, -1)

In [95]:
walks = steps.cumsum(axis=1)